Feature/5 get users
jyotikakrani25/SpringBoot_Tutorial pull request #9
Opened 2022-05-01 09:52 UTC by jyotikakrani25

Added integration test as part of this PR.

2022-05-01 11:33 UTC, habelMarottipuzha requested changes

2022-05-01 11:33 UTC, habelMarottipuzha commented on src/main/java/com/buddy/tutorial/controller/UserController.java
> +    @Autowired
whats the need for field based and constructor based injection. use any one

2022-05-01 11:33 UTC, habelMarottipuzha commented on src/main/java/com/buddy/tutorial/controller/UserController.java
> +    @PostMapping("/users")
move common path of all controllers to class level

2022-05-01 11:33 UTC, habelMarottipuzha commented on src/main/java/com/buddy/tutorial/service/UserServiceImpl.java
> +        } else if (query != null) {//select U* from users where name = %s and email = %s : select * from Users where name = buddy ,or email =
remove comment

2022-05-01 11:33 UTC, habelMarottipuzha commented on README.md
> +# Spring Boot tutorial
update readme. include more information regarding project. also include various steps to run check style, build etc..

2022-05-01 11:36 UTC, habelMarottipuzha commented on src/test/java/com/buddy/tutorial/controller/UserControllerIT.java
> +@SpringBootTest
use sliced tests here. https://developer.okta.com/blog/2021/07/12/spring-boot-test-slices     https://reflectoring.io/spring-boot-test/

2022-05-03 08:39 UTC, jyotikakrani25 commented on src/main/java/com/buddy/tutorial/service/UserServiceImpl.java
> +        } else if (query != null) {//select U* from users where name = %s and email = %s : select * from Users where name = buddy ,or email =
Done

2022-05-03 09:25 UTC, habelMarottipuzha commented on src/test/java/com/buddy/tutorial/TutorialApplicationTests.java
> +        Assertions.assertTrue(true);
Whas this?? add some test to test context

2022-05-15 15:50 UTC, habelMarottipuzha approved these changes

2022-05-15 15:51 UTC, merged